backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{title}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: work
    label: Work
    folder: content/work
    create: true
    slug: "{{title}}"
    fields:
      - { name: title, label: Title }
      - { name: year, label: Year }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: cover, label: Cover, widget: image }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Caption, name: caption}
